### ISSUE TITLE
RESULT: remote object '/sdcard/com.the42apps.jacocosamplejacoco.exec' does not exist

### ISSUE THREAD

**Issue by sunhao111999** [skyisle/gradle-jacoco-android#2]
@skyisle  

hi, from your sample, i get this error:

``` sh
RESULT: remote object '/sdcard/com.the42apps.jacocosamplejacoco.exec' does not exist
```

in AndroidManifest.xml, i add:

``` sh
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
```

but still error, please help!

**Comment by skyisle** [comment]
Did you specify test runner to com.alanjeon.testing.JacocoRunner?

**Comment by sunhao111999** [comment]
@skyisle  @ze12augusto 

yes, i did.  but now i got another error:

``` sh
D/JacocoRunner( 3025): endCoverage started!
D/JacocoRunner( 3025): java.lang.reflect.InvocationTargetException
D/JacocoRunner( 3025): java.lang.reflect.InvocationTargetException
D/JacocoRunner( 3025):  at java.lang.reflect.Method.invokeNative(Native Method)
D/JacocoRunner( 3025):  at java.lang.reflect.Method.invoke(Method.java:525)
D/JacocoRunner( 3025):  at com.alanjeon.testing.JacocoRunner.endCoverage(JacocoRunner.java:47)
D/JacocoRunner( 3025):  at com.alanjeon.testing.JacocoRunner.finish(JacocoRunner.java:82)
D/JacocoRunner( 3025):  at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner$BridgeTestRunner.finish(GoogleInstrumentationTestRunner.java:264)
D/JacocoRunner( 3025):  at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:574)
D/JacocoRunner( 3025):  at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner.onStart(GoogleInstrumentationTestRunner.java:167)
D/JacocoRunner( 3025):  at com.alanjeon.testing.JacocoRunner.onStart(JacocoRunner.java:74)
D/JacocoRunner( 3025):  at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
D/JacocoRunner( 3025): Caused by: java.lang.IllegalStateException: JaCoCo agent not started.
D/JacocoRunner( 3025):  at org.jacoco.agent.rt.internal_6effb9e.Agent.getInstance(Agent.java:72)
D/JacocoRunner( 3025):  at org.jacoco.agent.rt.RT.getAgent(RT.java:32)
D/JacocoRunner( 3025):  ... 9 more
I/GoogleInstr( 3025): Unstopped activity count: 1


```

**Comment by youdidut** [comment]
I am having the same issue here. Do you have any update on that?

**Comment by youdidut** [comment]
Is it because I am using an emulator instead of a real device?

**Comment by youdidut** [comment]
@sunhao111999 
I had the problem "RESULT: remote object '/sdcard/com.the42apps.jacocosamplejacoco.exec' does not exist ". Did you manage to solve it?

**Comment by youdidut** [comment]
After adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>,  the build it successful. But I am still not getting the report, even though I have got a non-empty jacoco.exec file.
